In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb

In [3]:
#Reading Metadata File
# Dataset Link: https://www.kaggle.com/datasets/rounakbanik/the-movies-dataset
df=pd.read_csv('../movies_metadata.csv')
df.head()

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_22180\2392175965.py:2: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv('../movies_metadata.csv')

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [4]:
df.dtypes

adult                     object
belongs_to_collection     object
budget                    object
genres                    object
homepage                  object
id                        object
imdb_id                   object
original_language         object
original_title            object
overview                  object
popularity                object
poster_path               object
production_companies      object
production_countries      object
release_date              object
revenue                  float64
runtime                  float64
spoken_languages          object
status                    object
tagline                   object
title                     object
video                     object
vote_average             float64
vote_count               float64
dtype: object

In [5]:
# id column unclean. keeping only the records that are clean (ID is numeric)
# Also Filtering out records with imdb_id empty (Required for attaining Movie Posters)
df['id'] = pd.to_numeric(df['id'], errors='coerce')
df = df.dropna(subset=['id'])
df['id'] = df['id'].astype('int32')
df = df[df['imdb_id'].notnull()]

In [6]:
df.id.dtypes

dtype('int32')

In [7]:
# sorting movies based on vote count (popularity)
df=df.sort_values(by='vote_count',ascending=False)
df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
15480,False,NaN,160000000,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",http://inceptionmovie.warnerbros.com/,27205,tt1375666,en,Inception,"Cobb, a skilled thief who commits corporate es...",...,2010-07-14,8.255328e+08,148.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Your mind is the scene of the crime.,Inception,False,8.1,14075.0
12481,False,"{'id': 263, 'name': 'The Dark Knight Collectio...",185000000,"[{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...",http://thedarkknight.warnerbros.com/dvdsite/,155,tt0468569,en,The Dark Knight,Batman raises the stakes in his war on crime. ...,...,2008-07-16,1.004558e+09,152.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Why So Serious?,The Dark Knight,False,8.3,12269.0
14551,False,"{'id': 87096, 'name': 'Avatar Collection', 'po...",237000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",http://www.avatarmovie.com/,19995,tt0499549,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",...,2009-12-10,2.787965e+09,162.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Enter the World of Pandora.,Avatar,False,7.2,12114.0
17818,False,"{'id': 86311, 'name': 'The Avengers Collection...",220000000,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",http://marvel.com/avengers_movie/,24428,tt0848228,en,The Avengers,When an unexpected enemy emerges and threatens...,...,2012-04-25,1.519558e+09,143.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Some assembly required.,The Avengers,False,7.4,12000.0
26564,False,"{'id': 448150, 'name': 'Deadpool Collection', ...",58000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",http://www.foxmovies.com/movies/deadpool,293660,tt1431045,en,Deadpool,Deadpool tells the origin story of former Spec...,...,2016-02-09,7.831130e+08,108.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Witness the beginning of a happy ending,Deadpool,False,7.4,11444.0

In [8]:
# Filtering out only the top 5000 popular movies
df_5000=df.head(5000)

In [9]:
# Filtering out only the relevant columns
df_5000_filteredcols=df_5000['id,title,imdb_id,overview,genres,tagline,production_companies'.split(',')]
df_5000_filteredcols.head()

,id,title,imdb_id,overview,genres,tagline,production_companies
15480,27205,Inception,tt1375666,"Cobb, a skilled thief who commits corporate es...","[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",Your mind is the scene of the crime.,"[{'name': 'Legendary Pictures', 'id': 923}, {'..."
12481,155,The Dark Knight,tt0468569,Batman raises the stakes in his war on crime. ...,"[{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...",Why So Serious?,"[{'name': 'DC Comics', 'id': 429}, {'name': 'L..."
14551,19995,Avatar,tt0499549,"In the 22nd century, a paraplegic Marine is di...","[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Enter the World of Pandora.,"[{'name': 'Ingenious Film Partners', 'id': 289..."
17818,24428,The Avengers,tt0848228,When an unexpected enemy emerges and threatens...,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",Some assembly required.,"[{'name': 'Paramount Pictures', 'id': 4}, {'na..."
26564,293660,Deadpool,tt1431045,Deadpool tells the origin story of former Spec...,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Witness the beginning of a happy ending,[{'name': 'Twentieth Century Fox Film Corporat...

In [10]:
# Reading credits file
df_credits=pd.read_csv('../credits.csv')
df_credits.head()

,cast,crew,id
0,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...",862
1,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...",8844
2,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...",15602
3,"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...",31357
4,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...",11862

In [11]:
# cleaning the id column (keeping records where id is nemeric)
df_credits['id'] = pd.to_numeric(df_credits['id'], errors='coerce')
df_credits = df_credits.dropna(subset=['id'])
df_credits['id'] = df_credits['id'].astype('int32')

In [12]:
# Performing inner join with df_5000_filteredcols dataframe. Should take into consideration the top 5000 movies previously filtered out from df_credits
df_combined=pd.merge(df_5000_filteredcols,df_credits,on='id',how='inner')
df_combined

,id,title,imdb_id,overview,genres,tagline,production_companies,cast,crew
0,27205,Inception,tt1375666,"Cobb, a skilled thief who commits corporate es...","[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",Your mind is the scene of the crime.,"[{'name': 'Legendary Pictures', 'id': 923}, {'...","[{'cast_id': 1, 'character': 'Dom Cobb', 'cred...","[{'credit_id': '56e8462cc3a368408400354c', 'de..."
1,155,The Dark Knight,tt0468569,Batman raises the stakes in his war on crime. ...,"[{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...",Why So Serious?,"[{'name': 'DC Comics', 'id': 429}, {'name': 'L...","[{'cast_id': 35, 'character': 'Bruce Wayne / B...","[{'credit_id': '55a0eb4a925141296b0010f8', 'de..."
2,19995,Avatar,tt0499549,"In the 22nd century, a paraplegic Marine is di...","[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Enter the World of Pandora.,"[{'name': 'Ingenious Film Partners', 'id': 289...","[{'cast_id': 242, 'character': 'Jake Sully', '...","[{'credit_id': '52fe48009251416c750aca23', 'de..."
3,24428,The Avengers,tt0848228,When an unexpected enemy emerges and threatens...,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",Some assembly required.,"[{'name': 'Paramount Pictures', 'id': 4}, {'na...","[{'cast_id': 46, 'character': 'Tony Stark / Ir...","[{'credit_id': '52fe4495c3a368484e02b1cf', 'de..."
4,293660,Deadpool,tt1431045,Deadpool tells the origin story of former Spec...,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Witness the beginning of a happy ending,[{'name': 'Twentieth Century Fox Film Corporat...,"[{'cast_id': 99, 'character': 'Wade Wilson / D...","[{'credit_id': '57e564fac3a3681beb0000cc', 'de..."
...,...,...,...,...,...,...,...,...,...
5005,60309,The Conspirator,tt0968264,Mary Surratt is the lone female charged as a c...,"[{'id': 80, 'name': 'Crime'}, {'id': 18, 'name...",One bullet killed the President. But not one man.,"[{'name': 'Wildwood Enterprises', 'id': 316}, ...","[{'cast_id': 3, 'character': 'Anna Surratt', '...","[{'credit_id': '52fe461fc3a368484e0801f3', 'de..."
5006,10013,Peggy Sue Got Married,tt0091738,Peggy Sue faints at a Highschool reunion. When...,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...","Knowing what you know now, what would you do d...","[{'name': 'American Zoetrope', 'id': 70}, {'na...","[{'cast_id': 2, 'character': 'Charlie Bodell',...","[{'credit_id': '52fe43079251416c75000b0f', 'de..."
5007,3682,54,tt0120577,"Shane, a Jersey boy with big dreams, crosses t...","[{'id': 10402, 'name': 'Music'}, {'id': 18, 'n...",You've never been anywhere until you've been here,"[{'name': 'Redeemable Features', 'id': 1483}, ...","[{'cast_id': 2, 'character': ""Shane O'Shea"", '...","[{'credit_id': '561fa61592514171cb003460', 'de..."
5008,256040,Baahubali: The Beginning,tt2631186,The young Shivudu is left as a foundling in a ...,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",NaN,"[{'name': 'Arka Media Works', 'id': 57946}]","[{'cast_id': 0, 'character': 'Shivudu / Baahub...","[{'credit_id': '55ace8129251411e180086ca', 'de..."
5009,81342,Delicacy,tt1828995,A French woman mourning over the death of her ...,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...","A new romantic comedy about Love, Fate, and ot...","[{'name': 'StudioCanal', 'id': 694}]","[{'cast_id': 1, 'character': 'Nathalie', 'cred...","[{'credit_id': '52fe480a9251416c9107e1a5', 'de..."

In [13]:
df_clean=df_combined.copy()

In [14]:
# Performing JSON parsing with ast. Columns genres and production companies have data stored within the 'name' field.
import ast
def extract_names(obj):
    try:
        return ", ".join([i['name'] for i in ast.literal_eval(obj)]) # Seperate values with a comma
    except:
        return ""

df_clean['genres'] = df_clean['genres'].apply(extract_names)
df_clean['production_companies'] = df_clean['production_companies'].apply(extract_names)

In [15]:
df_clean

,id,title,imdb_id,overview,genres,tagline,production_companies,cast,crew
0,27205,Inception,tt1375666,"Cobb, a skilled thief who commits corporate es...","Action, Thriller, Science Fiction, Mystery, Ad...",Your mind is the scene of the crime.,"Legendary Pictures, Warner Bros., Syncopy","[{'cast_id': 1, 'character': 'Dom Cobb', 'cred...","[{'credit_id': '56e8462cc3a368408400354c', 'de..."
1,155,The Dark Knight,tt0468569,Batman raises the stakes in his war on crime. ...,"Drama, Action, Crime, Thriller",Why So Serious?,"DC Comics, Legendary Pictures, Warner Bros., D...","[{'cast_id': 35, 'character': 'Bruce Wayne / B...","[{'credit_id': '55a0eb4a925141296b0010f8', 'de..."
2,19995,Avatar,tt0499549,"In the 22nd century, a paraplegic Marine is di...","Action, Adventure, Fantasy, Science Fiction",Enter the World of Pandora.,"Ingenious Film Partners, Twentieth Century Fox...","[{'cast_id': 242, 'character': 'Jake Sully', '...","[{'credit_id': '52fe48009251416c750aca23', 'de..."
3,24428,The Avengers,tt0848228,When an unexpected enemy emerges and threatens...,"Science Fiction, Action, Adventure",Some assembly required.,"Paramount Pictures, Marvel Studios","[{'cast_id': 46, 'character': 'Tony Stark / Ir...","[{'credit_id': '52fe4495c3a368484e02b1cf', 'de..."
4,293660,Deadpool,tt1431045,Deadpool tells the origin story of former Spec...,"Action, Adventure, Comedy",Witness the beginning of a happy ending,"Twentieth Century Fox Film Corporation, Marvel...","[{'cast_id': 99, 'character': 'Wade Wilson / D...","[{'credit_id': '57e564fac3a3681beb0000cc', 'de..."
...,...,...,...,...,...,...,...,...,...
5005,60309,The Conspirator,tt0968264,Mary Surratt is the lone female charged as a c...,"Crime, Drama, History",One bullet killed the President. But not one man.,"Wildwood Enterprises, American Film Company","[{'cast_id': 3, 'character': 'Anna Surratt', '...","[{'credit_id': '52fe461fc3a368484e0801f3', 'de..."
5006,10013,Peggy Sue Got Married,tt0091738,Peggy Sue faints at a Highschool reunion. When...,"Comedy, Drama, Fantasy, Romance","Knowing what you know now, what would you do d...","American Zoetrope, TriStar Pictures","[{'cast_id': 2, 'character': 'Charlie Bodell',...","[{'credit_id': '52fe43079251416c75000b0f', 'de..."
5007,3682,54,tt0120577,"Shane, a Jersey boy with big dreams, crosses t...","Music, Drama",You've never been anywhere until you've been here,"Redeemable Features, FilmColony, Miramax, Doll...","[{'cast_id': 2, 'character': ""Shane O'Shea"", '...","[{'credit_id': '561fa61592514171cb003460', 'de..."
5008,256040,Baahubali: The Beginning,tt2631186,The young Shivudu is left as a foundling in a ...,"Action, Adventure, History, War",NaN,Arka Media Works,"[{'cast_id': 0, 'character': 'Shivudu / Baahub...","[{'credit_id': '55ace8129251411e180086ca', 'de..."
5009,81342,Delicacy,tt1828995,A French woman mourning over the death of her ...,"Drama, Comedy, Romance","A new romantic comedy about Love, Fate, and ot...",StudioCanal,"[{'cast_id': 1, 'character': 'Nathalie', 'cred...","[{'credit_id': '52fe480a9251416c9107e1a5', 'de..."

In [16]:
# Performing JSON parsing for cast column. Since, cast list can be massive, only the first 5 cast members (main cast) will be taken into consideration
def get_top_cast(cast_str):
    try:
        cast_list = ast.literal_eval(cast_str)
        names = [member['name'] for member in cast_list[:5]]
        return ", ".join(names)
    except:
        return ""

# Performing JSON parsing for director column
def get_director(crew_str):
    try:
        crew_list = ast.literal_eval(crew_str)
        for member in crew_list:
            if member['job'] == 'Director':
                return member['name']
        return ""
    except:
        return ""

In [17]:
df_clean['cast'] = df_clean['cast'].apply(get_top_cast)
df_clean['director'] = df_clean['crew'].apply(get_director)

In [18]:
df_clean

,id,title,imdb_id,overview,genres,tagline,production_companies,cast,crew,director
0,27205,Inception,tt1375666,"Cobb, a skilled thief who commits corporate es...","Action, Thriller, Science Fiction, Mystery, Ad...",Your mind is the scene of the crime.,"Legendary Pictures, Warner Bros., Syncopy","Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen...","[{'credit_id': '56e8462cc3a368408400354c', 'de...",Christopher Nolan
1,155,The Dark Knight,tt0468569,Batman raises the stakes in his war on crime. ...,"Drama, Action, Crime, Thriller",Why So Serious?,"DC Comics, Legendary Pictures, Warner Bros., D...","Christian Bale, Michael Caine, Heath Ledger, A...","[{'credit_id': '55a0eb4a925141296b0010f8', 'de...",Christopher Nolan
2,19995,Avatar,tt0499549,"In the 22nd century, a paraplegic Marine is di...","Action, Adventure, Fantasy, Science Fiction",Enter the World of Pandora.,"Ingenious Film Partners, Twentieth Century Fox...","Sam Worthington, Zoe Saldana, Sigourney Weaver...","[{'credit_id': '52fe48009251416c750aca23', 'de...",James Cameron
3,24428,The Avengers,tt0848228,When an unexpected enemy emerges and threatens...,"Science Fiction, Action, Adventure",Some assembly required.,"Paramount Pictures, Marvel Studios","Robert Downey Jr., Chris Evans, Mark Ruffalo, ...","[{'credit_id': '52fe4495c3a368484e02b1cf', 'de...",Joss Whedon
4,293660,Deadpool,tt1431045,Deadpool tells the origin story of former Spec...,"Action, Adventure, Comedy",Witness the beginning of a happy ending,"Twentieth Century Fox Film Corporation, Marvel...","Ryan Reynolds, Morena Baccarin, Ed Skrein, T.J...","[{'credit_id': '57e564fac3a3681beb0000cc', 'de...",Tim Miller
...,...,...,...,...,...,...,...,...,...,...
5005,60309,The Conspirator,tt0968264,Mary Surratt is the lone female charged as a c...,"Crime, Drama, History",One bullet killed the President. But not one man.,"Wildwood Enterprises, American Film Company","Evan Rachel Wood, James McAvoy, Kevin Kline, R...","[{'credit_id': '52fe461fc3a368484e0801f3', 'de...",Robert Redford
5006,10013,Peggy Sue Got Married,tt0091738,Peggy Sue faints at a Highschool reunion. When...,"Comedy, Drama, Fantasy, Romance","Knowing what you know now, what would you do d...","American Zoetrope, TriStar Pictures","Nicolas Cage, Jim Carrey, Kathleen Turner, Hel...","[{'credit_id': '52fe43079251416c75000b0f', 'de...",Francis Ford Coppola
5007,3682,54,tt0120577,"Shane, a Jersey boy with big dreams, crosses t...","Music, Drama",You've never been anywhere until you've been here,"Redeemable Features, FilmColony, Miramax, Doll...","Ryan Phillippe, Salma Hayek, Breckin Meyer, Mi...","[{'credit_id': '561fa61592514171cb003460', 'de...",Mark Christopher
5008,256040,Baahubali: The Beginning,tt2631186,The young Shivudu is left as a foundling in a ...,"Action, Adventure, History, War",NaN,Arka Media Works,"Prabhas, Rana Daggubati, Tamanna Bhatia, Anush...","[{'credit_id': '55ace8129251411e180086ca', 'de...",S.S. Rajamouli
5009,81342,Delicacy,tt1828995,A French woman mourning over the death of her ...,"Drama, Comedy, Romance","A new romantic comedy about Love, Fate, and ot...",StudioCanal,"Audrey Tautou, François Damiens, Bruno Todesch...","[{'credit_id': '52fe480a9251416c9107e1a5', 'de...",Stéphane Foenkinos

In [ ]:
# Adding a column omdb_link which will be required later on in the project for linking movie posters
# df_clean['omdb_link']="http://www.omdbapi.com/?i="+df_clean['imdb_id']+"&apikey=xxxxxxxxxxx"
# df_clean.head()
### omdb_link removed after project completion as it contained API link

In [20]:
# dropping crew column
df_clean.drop(columns='crew',inplace=True)

In [22]:
df_clean.isnull().sum()

id                        0
title                     0
imdb_id                   0
overview                  6
genres                    0
tagline                 596
production_companies      0
cast                      0
director                  0
omdb_link                 0
dtype: int64

In [23]:
df_clean[df_clean.duplicated()].shape

(15, 10)

In [24]:
df_clean.drop_duplicates(keep='first',inplace=True)

In [25]:
df_clean.fillna('',inplace=True)

In [27]:
# creating tags column which takes into consideration overview, genres, cast, director and tagline columns. This column will be our key data field for text preparation and model building
df_clean['tags'] = (
    df_clean['overview'] + ' ' +
    df_clean['genres'] + ' ' +
    df_clean['cast'] + ' ' +
    df_clean['director'] + ' ' +
    df_clean['tagline']
)

In [29]:
# Saving dataframe as a csv file
df_clean.to_csv('MovieDataCleanedDataSet.csv',index=False)